apiVersion: v1
kind: Service
metadata:
  namespace: flink-standalone-session
  name: session-jm-service
spec:
  type: NodePort
  ports:
    - name: rpc
      port: 6123
    - name: blob
      port: 6124
    - name: ui
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: flink
    component: jobmanager
