FROM openjdk:8u342-jdk

# Set environment variables
ENV JAVA_HOME="/usr/local/openjdk-8/"
ENV PATH="/opt/apache-doris/fe/bin:/opt/apache-doris/fe/bin:$PATH"

# Download the software into the Docker image
COPY apache-doris-2.1.4-bin-arm64.tar.gz /opt/

RUN apt-get update && \
    apt-get install -y default-mysql-client && \
    apt-get clean && \
    mkdir /opt/apache-doris && \
    cd /opt && \
    tar -zxvf apache-doris-2.1.4-bin-arm64.tar.gz && \
    mv apache-doris-2.1.4-bin-arm64/fe /opt/apache-doris/ && \
    mv apache-doris-2.1.4-bin-arm64/be /opt/apache-doris/

ADD ./resource/init_fe.sh /opt/apache-doris/fe/bin
ADD ./resource/init_be.sh /opt/apache-doris/be/bin
RUN chmod 755 /opt/apache-doris/fe/bin/init_fe.sh
RUN chmod 755 /opt/apache-doris/be/bin/init_be.sh

ENTRYPOINT ["bash","entry_point.sh"]